"""Shared Pydantic data models used across the toolkit."""

from __future__ import annotations

import time
from typing import Callable

from pydantic import BaseModel, Field


class KeyFrame(BaseModel):
    """A key frame retained after frame-differencing, carrying a Base64 image."""

    frame_id: int
    timestamp_ms: int = Field(description="Timestamp relative to recording start (ms)")
    base64_image: str = Field(description="JPEG Base64-encoded string")
    created_at: float = Field(
        default_factory=time.monotonic,
        description="Monotonic clock, used for queue expiry checks",
    )


class FrameDescription(BaseModel):
    """Structured description returned by a VLM for a single frame."""

    frame_id: int
    timestamp_ms: int
    description: str = Field(description="Text description of the frame")


class VideoSummary(BaseModel):
    """Final video summary generated by a summarization model."""

    frame_descriptions: list[FrameDescription]
    summary_text: str
    total_keyframes: int
    duration_s: float


class FrameRecord(BaseModel):
    """Full record for a single sampled frame, including keyframe decision."""

    model_config = {"arbitrary_types_allowed": True}

    frame_idx: int
    timestamp_ms: int
    diff_value: float | None = Field(default=None, description="Diff vs previous keyframe")
    is_keyframe: bool = False
    reason: str = Field(default="", description="Keyframe decision reason")
    image_filename: str | None = Field(default=None, description="Saved image filename")
    vlm_response: str | None = Field(default=None, description="VLM response (keyframes only)")


class PipelineResult(BaseModel):
    """Complete pipeline run result."""

    frame_records: list[FrameRecord] = Field(default_factory=list)
    descriptions: list[FrameDescription] = Field(default_factory=list)
    summary: VideoSummary | None = None
    total_sampled: int = 0
    total_keyframes: int = 0
    total_dropped: int = 0
    duration_s: float = 0.0


class JudgeScore(BaseModel):
    """Scoring result from LLM-as-Judge evaluation."""

    asset_id: str
    model_id: str
    prompt_mode: str = Field(description="A_description or B_assistant")
    dimension_scores: dict[str, int] = Field(default_factory=dict)
    total_score: int = 0
    max_score: int = 10
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    missing_points: list[str] = Field(default_factory=list)
    hallucinations: list[str] = Field(default_factory=list)
    raw_response: str = ""


# Frame sampling callback signature:
# (frame_idx, timestamp_ms, frame_bgr, diff_value, is_keyframe, reason)
OnFrameSampledCallback = Callable[
    [int, int, "object", float | None, bool, str], None
]
